/* The following code was generated by JFlex 1.4.1 on 15.07.08 9:57 */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2004  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * This program is free software; you can redistribute it and/or modify    *
 * it under the terms of the GNU General Public License. See the file      *
 * COPYRIGHT for more information.                                         *
 *                                                                         *
 * This program is distributed in the hope that it will be useful,         *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
 * GNU General Public License for more details.                            *
 *                                                                         *
 * You should have received a copy of the GNU General Public License along *
 * with this program; if not, write to the Free Software Foundation, Inc., *
 * 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA                 *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* Java 1.2 language lexer specification */

/* Use together with unicode.flex for Unicode preprocesssing */
/* and java12.cup for a Java 1.2 parser                      */

/* Note that this lexer specification is not tuned for speed.
   It is in fact quite slow on integer and floating point literals, 
   because the input is read twice and the methods used to parse
   the numbers are not very fast. 
   For a production quality application (e.g. a Java compiler) 
   this could be optimized */

package tdo.tools.scanner;
import tdo.tools.expr.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 15.07.08 9:57 from the specification file
 * <tt>c:/jradarsolutions/TDOFlex/java.flex</tt>
 */
public class LScanner implements LexConst {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 1;
  public static final int YYINITIAL = 0;
  public static final int BETWEEN_STATE = 2;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\30\1\24\1\2\1\0\1\24\1\1\16\30\4\0\1\24\3\0"+
    "\1\27\2\0\1\63\1\53\1\54\1\26\1\61\1\55\1\41\1\40"+
    "\1\25\1\32\1\35\2\35\4\36\2\33\1\31\1\0\1\60\1\56"+
    "\1\57\2\0\1\5\1\13\1\22\1\34\1\14\1\37\1\20\1\23"+
    "\1\3\1\27\1\16\1\12\1\27\1\6\1\7\2\27\1\17\1\4"+
    "\1\10\1\11\1\27\1\15\1\21\2\27\1\0\1\42\2\0\1\27"+
    "\1\0\1\50\1\64\1\22\1\34\1\46\1\47\1\20\1\23\1\3"+
    "\1\27\1\16\1\51\1\27\1\65\1\7\2\27\1\44\1\52\1\43"+
    "\1\45\1\27\1\15\1\21\2\27\1\0\1\62\2\0\41\30\2\0"+
    "\4\27\4\0\1\27\2\0\1\30\7\0\1\27\4\0\1\27\5\0"+
    "\27\27\1\0\37\27\1\0\u013f\27\31\0\162\27\4\0\14\27\16\0"+
    "\5\27\11\0\1\27\21\0\130\30\5\0\23\30\12\0\1\27\13\0"+
    "\1\27\1\0\3\27\1\0\1\27\1\0\24\27\1\0\54\27\1\0"+
    "\46\27\1\0\5\27\4\0\202\27\1\0\4\30\3\0\105\27\1\0"+
    "\46\27\2\0\2\27\6\0\20\27\41\0\46\27\2\0\1\27\7\0"+
    "\47\27\11\0\21\30\1\0\27\30\1\0\3\30\1\0\1\30\1\0"+
    "\2\30\1\0\1\30\13\0\33\27\5\0\3\27\15\0\4\30\14\0"+
    "\6\30\13\0\32\27\5\0\13\27\16\30\7\0\12\30\4\0\2\27"+
    "\1\30\143\27\1\0\1\27\10\30\1\0\6\30\2\27\2\30\1\0"+
    "\4\30\2\27\12\30\3\27\2\0\1\27\17\0\1\30\1\27\1\30"+
    "\36\27\33\30\2\0\3\27\60\0\46\27\13\30\1\27\u014f\0\3\30"+
    "\66\27\2\0\1\30\1\27\20\30\2\0\1\27\4\30\3\0\12\27"+
    "\2\30\2\0\12\30\21\0\3\30\1\0\10\27\2\0\2\27\2\0"+
    "\26\27\1\0\7\27\1\0\1\27\3\0\4\27\2\0\1\30\1\27"+
    "\7\30\2\0\2\30\2\0\3\30\11\0\1\30\4\0\2\27\1\0"+
    "\3\27\2\30\2\0\12\30\4\27\15\0\3\30\1\0\6\27\4\0"+
    "\2\27\2\0\26\27\1\0\7\27\1\0\2\27\1\0\2\27\1\0"+
    "\2\27\2\0\1\30\1\0\5\30\4\0\2\30\2\0\3\30\13\0"+
    "\4\27\1\0\1\27\7\0\14\30\3\27\14\0\3\30\1\0\11\27"+
    "\1\0\3\27\1\0\26\27\1\0\7\27\1\0\2\27\1\0\5\27"+
    "\2\0\1\30\1\27\10\30\1\0\3\30\1\0\3\30\2\0\1\27"+
    "\17\0\2\27\2\30\2\0\12\30\1\0\1\27\17\0\3\30\1\0"+
    "\10\27\2\0\2\27\2\0\26\27\1\0\7\27\1\0\2\27\1\0"+
    "\5\27\2\0\1\30\1\27\6\30\3\0\2\30\2\0\3\30\10\0"+
    "\2\30\4\0\2\27\1\0\3\27\4\0\12\30\1\0\1\27\20\0"+
    "\1\30\1\27\1\0\6\27\3\0\3\27\1\0\4\27\3\0\2\27"+
    "\1\0\1\27\1\0\2\27\3\0\2\27\3\0\3\27\3\0\10\27"+
    "\1\0\3\27\4\0\5\30\3\0\3\30\1\0\4\30\11\0\1\30"+
    "\17\0\11\30\11\0\1\27\7\0\3\30\1\0\10\27\1\0\3\27"+
    "\1\0\27\27\1\0\12\27\1\0\5\27\4\0\7\30\1\0\3\30"+
    "\1\0\4\30\7\0\2\30\11\0\2\27\4\0\12\30\22\0\2\30"+
    "\1\0\10\27\1\0\3\27\1\0\27\27\1\0\12\27\1\0\5\27"+
    "\2\0\1\30\1\27\7\30\1\0\3\30\1\0\4\30\7\0\2\30"+
    "\7\0\1\27\1\0\2\27\4\0\12\30\22\0\2\30\1\0\10\27"+
    "\1\0\3\27\1\0\27\27\1\0\20\27\4\0\6\30\2\0\3\30"+
    "\1\0\4\30\11\0\1\30\10\0\2\27\4\0\12\30\22\0\2\30"+
    "\1\0\22\27\3\0\30\27\1\0\11\27\1\0\1\27\2\0\7\27"+
    "\3\0\1\30\4\0\6\30\1\0\1\30\1\0\10\30\22\0\2\30"+
    "\15\0\60\27\1\30\2\27\7\30\4\0\10\27\10\30\1\0\12\30"+
    "\47\0\2\27\1\0\1\27\2\0\2\27\1\0\1\27\2\0\1\27"+
    "\6\0\4\27\1\0\7\27\1\0\3\27\1\0\1\27\1\0\1\27"+
    "\2\0\2\27\1\0\4\27\1\30\2\27\6\30\1\0\2\30\1\27"+
    "\2\0\5\27\1\0\1\27\1\0\6\30\2\0\12\30\2\0\2\27"+
    "\42\0\1\27\27\0\2\30\6\0\12\30\13\0\1\30\1\0\1\30"+
    "\1\0\1\30\4\0\2\30\10\27\1\0\42\27\6\0\24\30\1\0"+
    "\2\30\4\27\4\0\10\30\1\0\44\30\11\0\1\30\71\0\42\27"+
    "\1\0\5\27\1\0\2\27\1\0\7\30\3\0\4\30\6\0\12\30"+
    "\6\0\6\27\4\30\106\0\46\27\12\0\51\27\7\0\132\27\5\0"+
    "\104\27\5\0\122\27\6\0\7\27\1\0\77\27\1\0\1\27\1\0"+
    "\4\27\2\0\7\27\1\0\1\27\1\0\4\27\2\0\47\27\1\0"+
    "\1\27\1\0\4\27\2\0\37\27\1\0\1\27\1\0\4\27\2\0"+
    "\7\27\1\0\1\27\1\0\4\27\2\0\7\27\1\0\7\27\1\0"+
    "\27\27\1\0\37\27\1\0\1\27\1\0\4\27\2\0\7\27\1\0"+
    "\47\27\1\0\23\27\16\0\11\30\56\0\125\27\14\0\u026c\27\2\0"+
    "\10\27\12\0\32\27\5\0\113\27\3\0\3\27\17\0\15\27\1\0"+
    "\4\27\3\30\13\0\22\27\3\30\13\0\22\27\2\30\14\0\15\27"+
    "\1\0\3\27\1\0\2\30\14\0\64\27\40\30\3\0\1\27\3\0"+
    "\2\27\1\30\2\0\12\30\41\0\3\30\2\0\12\30\6\0\130\27"+
    "\10\0\51\27\1\30\126\0\35\27\3\0\14\30\4\0\14\30\12\0"+
    "\12\30\36\27\2\0\5\27\u038b\0\154\27\224\0\234\27\4\0\132\27"+
    "\6\0\26\27\2\0\6\27\2\0\46\27\2\0\6\27\2\0\10\27"+
    "\1\0\1\27\1\0\1\27\1\0\1\27\1\0\37\27\2\0\65\27"+
    "\1\0\7\27\1\0\1\27\3\0\3\27\1\0\7\27\3\0\4\27"+
    "\2\0\6\27\4\0\15\27\5\0\3\27\1\0\7\27\17\0\4\30"+
    "\32\0\5\30\20\0\2\27\23\0\1\27\13\0\4\30\6\0\6\30"+
    "\1\0\1\27\15\0\1\27\40\0\22\27\36\0\15\30\4\0\1\30"+
    "\3\0\6\30\27\0\1\27\4\0\1\27\2\0\12\27\1\0\1\27"+
    "\3\0\5\27\6\0\1\27\1\0\1\27\1\0\1\27\1\0\4\27"+
    "\1\0\3\27\1\0\7\27\3\0\3\27\5\0\5\27\26\0\44\27"+
    "\u0e81\0\3\27\31\0\11\27\6\30\1\0\5\27\2\0\5\27\4\0"+
    "\126\27\2\0\2\30\2\0\3\27\1\0\137\27\5\0\50\27\4\0"+
    "\136\27\21\0\30\27\70\0\20\27\u0200\0\u19b6\27\112\0\u51a6\27\132\0"+
    "\u048d\27\u0773\0\u2ba4\27\u215c\0\u012e\27\2\0\73\27\225\0\7\27\14\0"+
    "\5\27\5\0\1\27\1\30\12\27\1\0\15\27\1\0\5\27\1\0"+
    "\1\27\1\0\2\27\1\0\2\27\1\0\154\27\41\0\u016b\27\22\0"+
    "\100\27\2\0\66\27\50\0\15\27\3\0\20\30\20\0\4\30\17\0"+
    "\2\27\30\0\3\27\31\0\1\27\6\0\5\27\1\0\207\27\2\0"+
    "\1\30\4\0\1\27\13\0\12\30\7\0\32\27\4\0\1\27\1\0"+
    "\32\27\12\0\132\27\3\0\6\27\2\0\6\27\2\0\6\27\2\0"+
    "\3\27\3\0\2\27\3\0\2\27\22\0\3\30\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\12\3\1\4\1\5\1\1\2\6"+
    "\1\7\1\10\2\3\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\1\1\20\1\21\2\22\1\1\1\23"+
    "\1\24\1\25\1\3\1\26\3\3\1\27\4\3\1\30"+
    "\1\31\1\0\1\32\1\33\1\34\1\32\2\3\1\35"+
    "\1\36\1\37\1\40\1\41\2\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\0\1\3\1\52\1\53"+
    "\5\3\1\32\1\0\2\3\1\42\1\0\1\3\1\0"+
    "\1\54\1\55\3\3\1\56\1\3\1\0\1\3\6\0"+
    "\1\3\1\57\1\3\1\60\1\61\1\3\1\62\5\0"+
    "\3\3\5\0\1\63\1\3\1\64\1\0\1\65\3\0"+
    "\1\3\3\0\1\66\1\0\1\3\4\0\1\67\2\0"+
    "\1\70\2\0\1\71\1\0\1\64\3\0\1\72\2\0"+
    "\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\242\0\u010e\0\u0144"+
    "\0\u017a\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4"+
    "\0\242\0\242\0\u032a\0\u0360\0\u0396\0\u03cc\0\242\0\u0402"+
    "\0\u0438\0\242\0\242\0\242\0\242\0\u046e\0\u04a4\0\242"+
    "\0\u04da\0\242\0\u0510\0\u0546\0\242\0\u057c\0\242\0\u05b2"+
    "\0\u021c\0\u05e8\0\u021c\0\u061e\0\u0654\0\u068a\0\u021c\0\u06c0"+
    "\0\u06f6\0\u072c\0\u0762\0\u0798\0\242\0\u07ce\0\u0804\0\242"+
    "\0\242\0\u083a\0\u0870\0\u08a6\0\242\0\242\0\242\0\242"+
    "\0\242\0\u08dc\0\u0912\0\242\0\242\0\242\0\242\0\242"+
    "\0\242\0\242\0\u0948\0\u097e\0\u021c\0\u09b4\0\u09ea\0\u0a20"+
    "\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\242"+
    "\0\u0bd0\0\u0c06\0\u0c3c\0\u021c\0\u021c\0\u0c72\0\u0ca8\0\u0cde"+
    "\0\u021c\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u0e22\0\u0e58"+
    "\0\u0e8e\0\u0ec4\0\u0efa\0\u021c\0\u0f30\0\u021c\0\242\0\u0f66"+
    "\0\242\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0"+
    "\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u021c\0\u125a"+
    "\0\u1290\0\u12c6\0\242\0\u12fc\0\u1332\0\u1368\0\u139e\0\u13d4"+
    "\0\u140a\0\u1440\0\242\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u154e"+
    "\0\u1584\0\u021c\0\u15ba\0\u15f0\0\242\0\u1626\0\u165c\0\u1692"+
    "\0\u16c8\0\242\0\u16fe\0\u1734\0\u176a\0\242\0\u17a0\0\u17d6"+
    "\0\242";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\2\14\1\15\1\16\3\14\1\17\2\14\1\20\1\14"+
    "\1\6\1\21\1\22\1\14\1\4\1\23\1\24\1\25"+
    "\1\14\2\25\1\14\1\26\1\27\1\4\1\30\1\17"+
    "\2\14\1\31\1\11\1\15\1\10\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\16\1\12"+
    "\1\43\1\44\1\45\37\43\1\46\20\43\1\47\2\43"+
    "\66\4\70\0\1\6\66\0\1\14\1\50\1\14\1\51"+
    "\15\14\3\0\2\14\1\0\6\14\3\0\7\14\1\50"+
    "\11\0\1\14\1\51\3\0\5\14\1\52\13\14\3\0"+
    "\2\14\1\0\6\14\3\0\1\52\7\14\11\0\2\14"+
    "\3\0\1\14\1\53\1\14\1\54\15\14\3\0\2\14"+
    "\1\0\6\14\3\0\7\14\1\53\11\0\1\14\1\54"+
    "\3\0\4\14\1\55\1\14\1\56\12\14\3\0\2\14"+
    "\1\0\6\14\3\0\2\14\1\56\5\14\11\0\2\14"+
    "\3\0\14\14\1\57\4\14\3\0\2\14\1\0\6\14"+
    "\3\0\1\14\1\57\6\14\11\0\2\14\3\0\21\14"+
    "\3\0\2\14\1\0\6\14\3\0\10\14\11\0\2\14"+
    "\3\0\1\60\20\14\3\0\2\14\1\0\6\14\3\0"+
    "\10\14\11\0\2\14\3\0\11\14\1\61\7\14\3\0"+
    "\2\14\1\0\6\14\3\0\3\14\1\61\4\14\11\0"+
    "\2\14\3\0\11\14\1\62\7\14\3\0\2\14\1\0"+
    "\6\14\3\0\3\14\1\62\4\14\11\0\2\14\3\0"+
    "\4\14\1\63\14\14\3\0\2\14\1\0\6\14\3\0"+
    "\10\14\11\0\2\14\3\0\21\64\3\0\1\64\4\0"+
    "\1\64\2\0\1\64\3\0\10\64\11\0\2\64\12\0"+
    "\1\65\1\0\1\66\15\0\2\67\1\70\2\67\1\71"+
    "\1\72\5\0\1\66\1\71\1\0\1\65\26\0\1\65"+
    "\1\0\1\66\15\0\2\25\1\70\2\25\1\71\1\72"+
    "\5\0\1\66\1\71\1\0\1\65\46\0\2\72\1\0"+
    "\2\72\32\0\21\14\3\0\2\14\1\0\6\14\3\0"+
    "\1\14\1\73\6\14\11\0\2\14\3\0\21\14\3\0"+
    "\2\14\1\0\6\14\3\0\5\14\1\74\2\14\11\0"+
    "\2\14\56\0\1\75\65\0\1\76\1\77\70\0\1\100"+
    "\3\0\1\43\2\0\37\43\1\0\20\43\1\0\2\43"+
    "\2\0\1\45\63\0\2\101\1\0\27\101\1\102\2\101"+
    "\1\102\1\103\3\101\1\104\1\105\1\106\2\101\1\107"+
    "\13\101\1\110\1\111\1\112\1\0\2\113\21\14\1\113"+
    "\2\0\2\14\1\0\6\14\3\0\10\14\11\0\2\14"+
    "\3\0\2\14\1\114\16\14\3\0\2\14\1\0\6\14"+
    "\3\0\5\14\1\114\2\14\11\0\2\14\3\0\21\14"+
    "\3\0\2\14\1\0\2\14\1\115\3\14\3\0\10\14"+
    "\11\0\2\14\3\0\5\14\1\116\13\14\3\0\2\14"+
    "\1\0\6\14\3\0\1\116\7\14\11\0\2\14\3\0"+
    "\7\14\1\117\11\14\3\0\2\14\1\0\6\14\3\0"+
    "\6\14\1\117\1\14\11\0\2\14\3\0\13\14\1\120"+
    "\5\14\3\0\2\14\1\0\6\14\3\0\10\14\11\0"+
    "\2\14\3\0\5\14\1\121\13\14\3\0\2\14\1\0"+
    "\6\14\3\0\1\121\7\14\11\0\2\14\3\0\15\14"+
    "\1\122\3\14\3\0\2\14\1\0\6\14\3\0\10\14"+
    "\11\0\2\14\3\0\3\14\1\123\15\14\3\0\2\14"+
    "\1\0\6\14\3\0\10\14\11\0\1\14\1\123\3\0"+
    "\21\64\3\0\2\64\1\0\6\64\3\0\10\64\11\0"+
    "\2\64\32\0\2\124\1\0\2\124\2\0\1\125\17\0"+
    "\1\125\20\0\1\66\15\0\2\67\1\70\2\67\1\71"+
    "\1\72\5\0\1\66\1\71\32\0\1\66\15\0\2\72"+
    "\1\70\2\72\1\71\6\0\1\66\1\71\21\0\21\14"+
    "\3\0\2\14\1\0\6\14\3\0\2\14\1\126\5\14"+
    "\11\0\2\14\3\0\21\14\3\0\2\14\1\0\6\14"+
    "\3\0\6\14\1\127\1\14\11\0\2\14\32\0\1\103"+
    "\2\0\2\103\61\0\1\130\2\0\2\130\30\0\2\113"+
    "\3\0\1\131\15\0\1\113\40\0\1\131\3\0\14\14"+
    "\1\132\4\14\3\0\2\14\1\0\6\14\3\0\1\14"+
    "\1\132\6\14\11\0\2\14\1\0\2\133\21\14\1\133"+
    "\2\0\2\14\1\0\6\14\3\0\10\14\11\0\2\14"+
    "\3\0\7\14\1\134\11\14\3\0\2\14\1\0\6\14"+
    "\3\0\6\14\1\134\1\14\11\0\2\14\3\0\11\14"+
    "\1\135\7\14\3\0\2\14\1\0\6\14\3\0\3\14"+
    "\1\135\4\14\11\0\2\14\3\0\12\14\1\136\6\14"+
    "\3\0\2\14\1\0\6\14\3\0\10\14\11\0\2\14"+
    "\3\0\11\14\1\137\7\14\3\0\2\14\1\0\6\14"+
    "\3\0\3\14\1\137\4\14\11\0\2\14\3\0\5\14"+
    "\1\140\13\14\3\0\2\14\1\0\6\14\3\0\1\140"+
    "\7\14\11\0\2\14\32\0\2\124\1\70\2\124\1\71"+
    "\7\0\1\71\50\0\2\124\1\0\2\124\32\0\21\14"+
    "\3\0\2\14\1\0\6\14\3\0\3\14\1\141\4\14"+
    "\11\0\2\14\3\0\21\14\3\0\2\14\1\0\6\14"+
    "\3\0\7\14\1\142\11\0\2\14\7\0\1\143\61\0"+
    "\5\14\1\144\13\14\3\0\2\14\1\0\6\14\3\0"+
    "\1\144\7\14\11\0\2\14\1\0\2\133\1\145\1\146"+
    "\5\0\1\147\1\150\3\0\1\151\2\0\1\152\1\0"+
    "\1\133\17\0\1\151\4\0\1\147\1\146\11\0\1\150"+
    "\4\0\11\14\1\153\7\14\3\0\2\14\1\0\6\14"+
    "\3\0\3\14\1\153\4\14\11\0\2\14\3\0\16\14"+
    "\1\154\2\14\3\0\2\14\1\0\6\14\3\0\10\14"+
    "\11\0\2\14\3\0\2\14\1\155\16\14\3\0\2\14"+
    "\1\0\6\14\3\0\5\14\1\155\2\14\11\0\2\14"+
    "\3\0\21\14\3\0\2\14\1\0\6\14\3\0\3\14"+
    "\1\156\4\14\11\0\2\14\10\0\1\157\32\0\1\157"+
    "\25\0\1\160\20\14\3\0\2\14\1\0\6\14\3\0"+
    "\10\14\11\0\2\14\6\0\1\161\56\0\1\161\10\0"+
    "\1\162\32\0\1\162\25\0\1\163\76\0\1\164\31\0"+
    "\1\164\33\0\1\165\31\0\1\165\26\0\1\166\61\0"+
    "\11\14\1\167\7\14\3\0\2\14\1\0\6\14\3\0"+
    "\3\14\1\167\4\14\11\0\2\14\3\0\1\170\20\14"+
    "\3\0\2\14\1\0\6\14\3\0\10\14\11\0\2\14"+
    "\3\0\3\14\1\171\15\14\3\0\2\14\1\0\6\14"+
    "\3\0\10\14\11\0\1\14\1\171\5\0\1\172\42\0"+
    "\1\172\33\0\1\173\57\0\1\174\32\0\1\174\42\0"+
    "\1\175\53\0\1\176\56\0\1\176\3\0\3\14\1\177"+
    "\15\14\3\0\2\14\1\0\6\14\3\0\10\14\11\0"+
    "\1\14\1\177\3\0\3\14\1\200\15\14\3\0\2\14"+
    "\1\0\6\14\3\0\10\14\11\0\1\14\1\200\3\0"+
    "\15\14\1\201\3\14\3\0\2\14\1\0\6\14\3\0"+
    "\10\14\11\0\2\14\17\0\1\202\24\0\1\202\35\0"+
    "\1\203\31\0\1\203\34\0\1\204\64\0\1\205\31\0"+
    "\1\205\27\0\1\206\32\0\1\206\25\0\1\207\20\14"+
    "\3\0\2\14\1\0\6\14\3\0\10\14\11\0\2\14"+
    "\1\0\2\210\21\14\1\210\2\0\2\14\1\0\6\14"+
    "\3\0\10\14\11\0\2\14\10\0\1\211\32\0\1\211"+
    "\36\0\1\212\31\0\1\212\40\0\1\213\51\0\1\214"+
    "\42\0\1\214\20\0\3\14\1\215\15\14\3\0\2\14"+
    "\1\0\6\14\3\0\10\14\11\0\1\14\1\215\1\0"+
    "\2\210\12\0\1\216\6\0\1\210\44\0\1\217\76\0"+
    "\1\220\31\0\1\220\22\0\1\221\65\0\15\14\1\222"+
    "\3\14\3\0\2\14\1\0\6\14\3\0\10\14\11\0"+
    "\2\14\3\0\1\223\70\0\1\224\56\0\1\224\6\0"+
    "\1\225\56\0\1\225\6\0\1\226\56\0\1\226\10\0"+
    "\1\227\32\0\1\227\42\0\1\230\50\0\1\231\105\0"+
    "\1\232\43\0\2\233\21\0\1\233\47\0\1\234\56\0"+
    "\1\234\1\0\2\233\12\0\1\235\6\0\1\233\61\0"+
    "\1\236\50\0\1\237\72\0\1\240\32\0\1\240\45\0"+
    "\1\241\42\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6156];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\12\1\2\11\4\1\1\11"+
    "\2\1\4\11\2\1\1\11\1\1\1\11\2\1\1\11"+
    "\1\1\1\11\15\1\1\11\1\0\1\1\2\11\3\1"+
    "\5\11\2\1\7\11\1\0\11\1\1\0\2\1\1\11"+
    "\1\0\1\1\1\0\7\1\1\0\1\1\6\0\4\1"+
    "\1\11\1\1\1\11\5\0\3\1\5\0\3\1\1\0"+
    "\1\11\3\0\1\1\3\0\1\11\1\0\1\1\4\0"+
    "\1\1\2\0\1\11\2\0\1\1\1\0\1\11\3\0"+
    "\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }

  /** 
   * assumes correct representation of a long value for 
   * specified radix in scanner buffer from <code>start</code> 
   * to <code>end</code> 
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1796) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public tdo.tools.expr.Symbol nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { /* ignore */
          }
        case 59: break;
        case 26: 
          { return symbol(FLOATING_POINT_LITERAL, new Double(yytext()));
          }
        case 60: break;
        case 20: 
          { return symbol(ISNULL);
          }
        case 61: break;
        case 13: 
          { return symbol(GT);
          }
        case 62: break;
        case 32: 
          { return symbol(CONCAT);
          }
        case 63: break;
        case 38: 
          { string.append( '\f' );
          }
        case 64: break;
        case 8: 
          { return symbol(MINUS);
          }
        case 65: break;
        case 14: 
          { return symbol(LT);
          }
        case 66: break;
        case 53: 
          { return symbol(NOTLIKE);
          }
        case 67: break;
        case 50: 
          { return symbol(NOTIN);
          }
        case 68: break;
        case 40: 
          { string.append( '\b' );
          }
        case 69: break;
        case 7: 
          { return symbol(DOT);
          }
        case 70: break;
        case 31: 
          { return symbol(NOTEQ);
          }
        case 71: break;
        case 6: 
          { return symbol(INTEGER_LITERAL, new Integer(yytext()));
          }
        case 72: break;
        case 15: 
          { return symbol(PLUS);
          }
        case 73: break;
        case 11: 
          { return symbol(COMMA);
          }
        case 74: break;
        case 36: 
          { string.append( '\t' );
          }
        case 75: break;
        case 48: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(false));
          }
        case 76: break;
        case 9: 
          { return symbol(LPAREN);
          }
        case 77: break;
        case 44: 
          { return symbol(NULL_LITERAL);
          }
        case 78: break;
        case 39: 
          { string.append( '\'' );
          }
        case 79: break;
        case 57: 
          { return symbol(NOTSTARTINGWITH);
          }
        case 80: break;
        case 5: 
          { return symbol(MULT);
          }
        case 81: break;
        case 18: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 82: break;
        case 58: 
          { return symbol(NOTCONTAINING);
          }
        case 83: break;
        case 43: 
          { return symbol(NOT);
          }
        case 84: break;
        case 42: 
          { return symbol(AND);
          }
        case 85: break;
        case 3: 
          { return symbol(IDENTIFIER, yytext());
          }
        case 86: break;
        case 24: 
          { return symbol(PARAMETER, yytext());
          }
        case 87: break;
        case 45: 
          { return symbol(LIKE);
          }
        case 88: break;
        case 4: 
          { return symbol(DIV);
          }
        case 89: break;
        case 25: 
          { return symbol(INTEGER_LITERAL, new Long(yytext().substring(0,yylength()-1)));
          }
        case 90: break;
        case 54: 
          { return symbol(NOTREGEX);
          }
        case 91: break;
        case 51: 
          { return symbol(BETWEEN);
          }
        case 92: break;
        case 23: 
          { return symbol(OR);
          }
        case 93: break;
        case 21: 
          { return symbol(IN);
          }
        case 94: break;
        case 12: 
          { return symbol(EQ);
          }
        case 95: break;
        case 30: 
          { return symbol(LTEQ);
          }
        case 96: break;
        case 22: 
          { return symbol(AS);
          }
        case 97: break;
        case 49: 
          { return symbol(ISNOTNULL);
          }
        case 98: break;
        case 46: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(true));
          }
        case 99: break;
        case 10: 
          { return symbol(RPAREN);
          }
        case 100: break;
        case 52: 
          { return symbol(STARTINGWITH);
          }
        case 101: break;
        case 47: 
          { return symbol(REGEX);
          }
        case 102: break;
        case 37: 
          { string.append( '\r' );
          }
        case 103: break;
        case 16: 
          { yybegin(STRING); string.setLength(0);
          }
        case 104: break;
        case 35: 
          { string.append( '\\' );
          }
        case 105: break;
        case 1: 
          { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
          }
        case 106: break;
        case 41: 
          { string.append( '\n' );
          }
        case 107: break;
        case 34: 
          { char val = (char) Integer.parseInt(yytext().substring(1),8);
                               string.append( val );
          }
        case 108: break;
        case 19: 
          { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
          }
        case 109: break;
        case 27: 
          { return symbol(FLOATING_POINT_LITERAL, new Double(yytext().substring(0,yylength()-1)));
          }
        case 110: break;
        case 55: 
          { return symbol(CONTAINING);
          }
        case 111: break;
        case 17: 
          { string.append( yytext() );
          }
        case 112: break;
        case 28: 
          { return symbol(FLOATING_POINT_LITERAL, new Float(yytext().substring(0,yylength()-1)));
          }
        case 113: break;
        case 33: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 114: break;
        case 56: 
          { return symbol(NOTBETWEEN);
          }
        case 115: break;
        case 29: 
          { return symbol(GTEQ);
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return symbol(EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
